buzden/deptycheck

- .github/workflows/ci-deptycheck.yml
Docker image for `idris2api` is somewhy updated not as often as `idris2` image, but here we don't need Idris API for tests.
> [ ci ] Use simpler and more adequate container image for GitHub CI

- .github/workflows/ci-deptycheck.yml
According to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> [ ci ] Replace deprecated feature with a functional equivalent

- tests/gen-derivation/derivation/distribution/vect-nat-001/CheckDistribution.idr
- tests/gen-derivation/derivation/distribution/vect-nat-001/DistrCheckCommon.idr
- tests/gen-derivation/derivation/distribution/vect-nat-001/expected
- tests/gen-derivation/derivation/distribution/vect-nat-001/run
- tests/gen-derivation/derivation/distribution/vect-nat-001/test.ipkg
This test is, actually, trickier that it looks ;-) If the given fuel is less than the given length, then no values could be generated, since we spend fuel in this recursive calls in the current state of derived generators.
> [ re #58 ] Add one more non-mutual-recursion no-fuel-spend test

- tests/gen-derivation/derivation/_common/PrintDerivation.idr
- tests/gen-derivation/derivation/_common/run
This is an alternative solution to #65, which does not rely on idris-lang/Idris2#2977 or a new core, since the script is still run in the top-level mode, not in an expression mode.
Closes #65
> [ test ] Speed up print tests, `declare` main with elab script

- src/Deriving/DepTyCheck/Gen/Core/ConsDerive.idr
This is similar to an old simplification hack by the fact that it takes only a single order into account, but it differs by that the only order used is like the original (before the hack) one.
The hack is turned off by default, but can be set to be used by defining a `default` implicit parameter of the `LeastEffort` constructors derivator.
> [ hack ] An alternative version of the simplification hack

- src/Deriving/DepTyCheck/Gen/Checked.idr
- tests/derivation/infra/ext print 004/expected
- tests/derivation/least-effort/print/adt/004 noparam/expected
- tests/derivation/least-effort/print/adt/006 param/expected
- tests/derivation/least-effort/print/adt/007 right-to-left simple/expected
- tests/derivation/least-effort/print/adt/008 right-to-left simple/expected
- tests/derivation/least-effort/print/adt/009 left-to-right/expected
- tests/derivation/least-effort/print/adt/010 right-to-left long-dpair/expected
- tests/derivation/least-effort/print/adt/011 right-to-left long-dpair/expected
- tests/derivation/least-effort/print/adt/012 right-to-left chained/expected
- tests/derivation/least-effort/print/adt/013 right-to-left nondet/expected
- tests/derivation/least-effort/print/adt/014 right-to-left nondet ext/expected
- tests/derivation/least-effort/print/gadt/002 gadt/expected
- tests/derivation/least-effort/print/gadt/003 right-to-left nondet/expected
- tests/derivation/least-effort/print/gadt/004 right-to-left det/expected
- tests/derivation/least-effort/print/gadt/005 gadt/expected
- tests/derivation/least-effort/print/gadt/006 gadt/expected
- tests/derivation/least-effort/print/gadt/007 eq-n/expected
Since this should reduce the monadic depth during derivation, this should increase the performance of the derivation
> [ performance ] Change the order of derivation, derive one strictly after another

- .gitlab/master.yml
Particular used path has disappeared
> [ ci, gl ] Don't use external job definition for super-linter

- src/Deriving/DepTyCheck/Gen/Checked.idr
- src/Deriving/DepTyCheck/Gen/Core.idr
- src/Deriving/DepTyCheck/Gen/Core/ConsDerive.idr
- src/Deriving/DepTyCheck/Gen/Derive.idr
- src/Deriving/DepTyCheck/Gen/Entry.idr
- src/Deriving/DepTyCheck/Util/Reflection.idr
> [ refactor ] Make `hasNamesInsideDeep` pure, precompute needed info

- src/Deriving/DepTyCheck/Gen/Checked.idr
- src/Deriving/DepTyCheck/Gen/Core/ConsDerive.idr
- src/Deriving/DepTyCheck/Gen/Core/ConsEntry.idr
- src/Deriving/DepTyCheck/Gen/Core/Util.idr
- src/Deriving/DepTyCheck/Gen/Derive.idr
- src/Deriving/DepTyCheck/Gen/Entry.idr
- src/Deriving/DepTyCheck/Util/Reflection.idr
- src/Language/Reflection/Compat.idr
- tests/derivation/_common/AlternativeCore.idr
- tests/derivation/utils/arg-deps/_common/Infra.idr
- tests/derivation/utils/canonicsig/_common/Infra.idr
- tests/derivation/utils/cons-analysis/_common-deep-cons-app/Infra.idr
- tests/derivation/utils/cons-analysis/deep-cons-app-006/ConsApps.idr
- tests/lib/coverage/ty-and-con-withCov-007/PrintCoverage.idr
Implements one or two next steps from #136
> [ cleanup ] Use the modern `Arg` type from `elab-util`

- .github/workflows/ci-deptycheck.yml
- .gitlab/deptycheck.yml
Attempt to workaround some flacky bug with late installation of `summary-stat` in GH CI
> [ ci ] Install `summary-stat` once at the beginning

- src/Deriving/DepTyCheck/Gen/Core.idr
Fixes #155. We can't just `%hide` function `when` from `Bernardy.Combinators` because it should reside in not-yet published collection
> [ upstream, workaround ] Disambiguate strangely conflicting definition

- .github/workflows/ci-deptycheck.yml
- .gitlab/deptycheck.yml
- src/Test/DepTyCheck/Gen.idr
Closes #157, for successfully built pack collections this does not make much difference, because collection must be built several minutes prior.
> [ ci ] Build nightly on `pack`'s `HEAD`, not `latest` + small useful function

- src/Deriving/DepTyCheck/Util/Collections.idr
Utility to create all possible (preserving order of given arguments) combinations from a Vect of Lists. E.g.:
```
Deriving.DepTyCheck.Util.Collections> combinations [1:::Nil, 2:::[3], 4:::[5,6]]
[1, 2, 4] ::: [[1, 3, 4], [1, 2, 5], [1, 3, 5], [1, 2, 6], [1, 3, 6]]
```
> [ collection ] Add combintaions function to collections sublib

- src/Deriving/DepTyCheck/Gen/Core/ConsDerive.idr
Two independently found problems fixed in two different commits
> [ derive, fix ] Small derivation-related performance fixes

- src/Deriving/DepTyCheck/Gen/Core/ConsDerive.idr
- src/Deriving/DepTyCheck/Util/Reflection.idr
> [ derive, refactor, perf ] Refactor `TypeApp`, make derivation faster

- docs/source/explanation/specifications/experiments.md
- examples/pil-fun/src/Language/PilFun/Derived.idr
- examples/pil-fun/src/Language/PilFun/Pretty/Derived.idr
- examples/sorted-list-so-comp/src/Data/List/Sorted/Gen.idr
- examples/sorted-list-so-full/src/Data/List/Sorted/Gen.idr
- examples/sorted-list-tl-pred/src/Data/List/Sorted/Gen.idr
- examples/sorted-tree-indexed/src/Data/SortedBinTree/Gen.idr
- examples/sorted-tree-naive/src/Data/SortedBinTree/Gen.idr
- examples/uniq-list/src/Data/List/Uniq/Gen.idr
- examples/uniq-list/src/Data/Vect/Uniq/Gen.idr
- src/Deriving/DepTyCheck/Gen/Core/ConsDerive.idr
- tests/derivation/_common/derive.ipkg
- tests/derivation/distribution/dependent-rec-sh-001/CheckDistribution.idr
- tests/derivation/distribution/dependent-rec-sh-002/CheckDistribution.idr
- tests/derivation/inputvalidation/_common/validate-input.ipkg
- tests/derivation/utils/arg-deps/_common/arg-deps.ipkg
- tests/derivation/utils/canonicsig/_common/canonic-sig.ipkg
- tests/derivation/utils/cons-analysis/_common-deep-cons-app/cons.ipkg
- tests/derivation/utils/involved-types/_common-involved-types/inv-ty.ipkg
- tests/derivation/utils/up-to-renaming-ttimp-eq/_common/renaming-ttimp-eq.ipkg
- tests/docs/readme/test.ipkg
Now, after #183, this option does not change anything.
If you are using a `%hint` with this option being set, and you get a compilation error, you can just remove this `%hint` and everything should work as before.
> [ breaking, cleanup ] Remove now unused `simplificationHack` derivator's option

- deptycheck.ipkg
- examples/sorted-list-so-comp/tests/gens/print/expected
- tests/derivation/infra/empty-cons print 015/expected
- tests/derivation/inputvalidation/bad-param-names/ValidateInput.idr
- tests/derivation/inputvalidation/bad-param-names/expected
- tests/derivation/inputvalidation/odd-or-lacking-gen-params/ValidateInput.idr
- tests/derivation/inputvalidation/odd-or-lacking-gen-params/expected
- tests/derivation/inputvalidation/unexpected-gen-target/expected
- tests/derivation/least-effort/print/regression/dependent-givens-impl-big/expected
- tests/derivation/least-effort/print/regression/undefined-name-impl-parameter/expected
- tests/derivation/least-effort/print/regression/underscore-in-cons-expl-full-gend1/expected
- tests/derivation/least-effort/print/regression/underscore-in-cons-expl-full-gend2/expected
- tests/derivation/least-effort/print/regression/underscore-in-cons-expl-full/expected
- tests/derivation/least-effort/print/regression/underscore-in-cons-expl-partial/expected
- tests/derivation/least-effort/print/regression/underscore-in-cons-impl-full/expected
- tests/derivation/utils/cons-analysis/deep-cons-app-006/expected
> [ test ] Add tests for error msgs when there are bad function arguments

- .github/workflows/ci-deptycheck.yml
- .github/workflows/ci-non-primary-os.yml
- .github/workflows/ci-super-linter.yml
This PR contains 2 changes in workflow:
1. Run CI on any push, not just in `main` and `master`.
2. Disable scheduled launches in forks. Usually they are only needed in the main repository. A similar condition is used in many projects, e.g.:
https://github.com/pypa/virtualenv/blob/27a1138dccd39e2f7fdcb3371c7e8a0c8b50f144/.github/workflows/check.yaml#L18
> [ ci ] Run workflow on any push and disable cron in forks

- .github/workflows/ci-deptycheck.yml
- .github/workflows/ci-non-primary-os.yml
- .github/workflows/ci-super-linter.yml
GitHub shows all the workflow runs for the corresponding commit in the pull request, so we can just skip the runs for PR triggers from the same repository.
> [ ci ] Prevent double running on the same branch

- .github/workflows/ci-deptycheck.yml
- .github/workflows/ci-non-primary-os.yml
- .github/workflows/ci-super-linter.yml
It makes cancelled jobs to not to appear in the status + does technical jobs of reading the repo state earlier
> [ ci ] Tune slightly gh ci

- src/Deriving/DepTyCheck/Gen/Core/ConsEntry.idr
- tests/derivation/least-effort/print/regression/determined-noncons-given-add/expected
- tests/derivation/least-effort/print/regression/determined-noncons-given-complex/expected
- tests/derivation/least-effort/print/regression/determined-noncons-given-impl/DerivedGen.idr
- tests/derivation/least-effort/print/regression/determined-noncons-given-impl/derive.ipkg
- tests/derivation/least-effort/print/regression/determined-noncons-given-impl/expected
- tests/derivation/least-effort/print/regression/determined-noncons-given-impl/run
- tests/derivation/least-effort/print/regression/determined-noncons-given-simple/expected
- tests/derivation/least-effort/run/regression/determined-noncons-given-impl/DerivedGen.idr
- tests/derivation/least-effort/run/regression/determined-noncons-given-impl/RunDerivedGen.idr
- tests/derivation/least-effort/run/regression/determined-noncons-given-impl/derive.ipkg
- tests/derivation/least-effort/run/regression/determined-noncons-given-impl/expected
- tests/derivation/least-effort/run/regression/determined-noncons-given-impl/run
> [ fix ] Rename bound implicits in a determined non-cons expressions

- src/Test/DepTyCheck/Gen.idr
This fixes some small errors that occur when building with the latest Idris head
> [ compat ] adjust to upstream changes
